# Generated by Django 3.1.7 on 2021-04-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.FloatField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_no', models.FloatField()),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DealLocation',
            fields=[
                ('rating', models.FloatField(blank=True, null=True)),
                ('location_id', models.FloatField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'deal_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('rating', models.FloatField(blank=True, null=True)),
                ('agency_id', models.FloatField(primary_key=True, serialize=False)),
                ('agen_name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index_1.deallocation')),
            ],
            options={
                'db_table': 'travel_agency',
                'managed': True,
            },
        ),
    ]
