# Generated by Django 3.1.7 on 2021-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='ph_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
